package com.ac.csun.team3;

import android.app.Activity;
import android.content.ActivityNotFoundException;
import android.content.Intent;
import android.os.Build;
import android.os.Bundle;
import android.speech.RecognizerIntent;
import android.speech.tts.TextToSpeech;
import android.util.Log;
import android.view.View;
import android.widget.LinearLayout;
import android.widget.TextView;
import android.widget.Toast;

import java.util.ArrayList;
import java.util.Locale;
/**
 * Created by the team on 2/4/2017.
 * Functional Capcha Replacement Page. Asks the user a random simple math question (via voice)
 * Expects an answer via voice.
 * Includes 'Speak your answer', 'Repeat question', and 'Try a new question' buttons.
 * Questions are generated by QuestionGenerator.
 * If a correct answer is given, advances to Victory
 * If an incorrect answer is given, two additional attempts are available. (Same or different Q.)
 * If 3 incorrect answers are given, advances to Defeat.
 * Also unlike the rest of the screens, this full screen is actually not a button.
 */
public class Listening extends Activity {
    private QuestionGenerator randQuestion; //Instantiate for a new question
    private static final int MAX_TRIES = 3;
    private TextToSpeech tts;
    int counter = 0; //Incorrect answers given so far.


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_listening);

        randQuestion = new QuestionGenerator(); //"Instantiate for a new question"


        LinearLayout LL = (LinearLayout) findViewById(R.id.activity_listening);
        LL.setBackgroundColor(LaunchActivity.col);
        TextView RCBT, REBT, SBT;
        RCBT = (TextView) findViewById(R.id.record_button_text);
        REBT = (TextView) findViewById(R.id.repeat_button_text);
        SBT = (TextView) findViewById(R.id.skip_button_text);
        RCBT.setTextColor(LaunchActivity.txt);
        REBT.setTextColor(LaunchActivity.txt);
        SBT.setTextColor(LaunchActivity.txt);

        //create Text To Speech, to ask a question
        tts = new TextToSpeech(this, new TextToSpeech.OnInitListener() {
            @Override
            public void onInit(int status) {
                if (status == TextToSpeech.SUCCESS) {
                    int result = tts.setLanguage(Locale.US);
                    if (result == TextToSpeech.LANG_MISSING_DATA ||
                            result == TextToSpeech.LANG_NOT_SUPPORTED) {
                        Log.e("TTS", "This Language is not supported");
                    }
                    speak(randQuestion.question);

                } else {
                    Log.e("TTS", "Initilization Failed!");
                }
            }
        });

        //Event listener, Mic button. Press to engage audio input to answer a question.
        findViewById(R.id.micButton).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                listen();
            }
        });

        //Event listener, Repeat button. Repeats current question.
        findViewById(R.id.replayButton).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                speak(randQuestion.question);
            }
        });

        //Event listener, Skip Button. Generates a new question and speaks it.
        findViewById(R.id.skipButton).setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View v) {
                randQuestion = new QuestionGenerator();
                speak(randQuestion.question);
            }
        });
    }

    //"... and enter". (Speak a line of text. Used for both asking questions,
    //and stating correct or incorrect
    private void speak(String text) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            //catch for API changes
            tts.speak(text, TextToSpeech.QUEUE_FLUSH, null, null);
        } else {
            tts.speak(text, TextToSpeech.QUEUE_FLUSH, null);
        }
    }

    //Audio listener, part 1. Button press activates listening for an answer.
    private void listen() {
        //set up params for intent listener
        Intent i = new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);
        i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,
                RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);
        i.putExtra(RecognizerIntent.EXTRA_LANGUAGE, Locale.getDefault());
        i.putExtra(RecognizerIntent.EXTRA_PROMPT, "Say something");

        //Listen to your heart. Er, question answer.
        try {
            startActivityForResult(i, 100);
        } catch (ActivityNotFoundException a) {
            Toast.makeText(Listening.this,
                    "Your device doesn't support Speech Recognition", Toast.LENGTH_SHORT).show();
        }
    }

    //Audio listener, part 2. Receives the resulting speech, parsed into text.
    //Thank you Google for building this API into the OS...
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        //get user input here
        if (requestCode == 100) {
            if (resultCode == RESULT_OK && null != data) {
                ArrayList<String> res =
                        data.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);
                String inSpeech = res.get(0);
                recognition(inSpeech);
            }
        }
    }

    //Audio listener, part 3. Takes the received answer and compares it to the correct answer.
    //Decides correct or incorrect, and Victory or Defeat.
    private void recognition(String text) {
        Log.e("Speech", "" + text);

        if (text.equals("" + randQuestion.answer) || text.equals("" + randQuestion.answer)) {
           // Log.i("Feedback", "That is correct!"+ randQuestion.answer);
            speak("Correct! ");
            startActivity(new Intent(Listening.this,Victory.class));
        } else {
            Log.i("Feedback", "incorrect!" + randQuestion.answer);
            counter++;
            int triesLeft =  MAX_TRIES - counter;
            speak("Incorrect!, You have " + triesLeft + " tries left");
            if (counter >= MAX_TRIES) {
                //Log.i("Feedback", "Max tries reached.");
                startActivity(new Intent(Listening.this,Defeat.class));
            }
        }
    }

        //Good-night.
        @Override
        public void onDestroy () {
            if (tts != null) {
                tts.stop();
                tts.shutdown();
            }
            super.onDestroy();
        }

    }

